# Site settings
title: Phonon Framework
description: A light weight, scalable and customizable HTML5 Hybrid Mobile App Framework working with Cordova. UI components inspired by Google Material Design.
baseurl: "/Phonon-Framework" # the subpath
url: "http://quarkdev.com" # the base hostname & protocol for your site
github_username: quark-dev

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - node_modules